name: flutter_kit
description: Debug tools for Flutter.
version: 0.0.2
homepage: https://code.addcn.com/flutter/flutter_kit
publish_to: http://192.168.8.75:4000/

environment:
  sdk: ">=2.17.3 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  shared_preferences: ^2.0.15
  vm_service: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

